---
  version: 2
  updates:
    - package-ecosystem: composer
      directory: .
      labels:
        - dependencies
        - php
        - 'ready to merge'
      schedule:
        interval: daily
        time: '00:00'
      open-pull-requests-limit: 99
    - package-ecosystem: docker
      directory: ./docker
      labels:
        - dependencies
        - docker
        - 'ready to merge'
      schedule:
        interval: daily
        time: '00:00'
