version: '2.0'

services:
  adminer:
    image: adminer
    restart: on-failure
    ports:
    - 8080:8080

  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_USER: taste
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knp_taste
    volumes:
      - './mysql:/var/lib/mysql'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
    user: ${LOCAL_USER}

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './public/:/usr/src/app'
    depends_on:
      - php
    ports:
      - 80:80