homepage:
  path: /
  controller: App\Controller\CourseController:homepageAction
view_all_courses:
  path: /courses
  controller: App\Controller\CourseController:viewAllCourses
view_course:
  path: /course/{id}
  controller: App\Controller\CourseController:viewCourse