App\Entity\Course:
    type: entity
    table: course
    id:
        id:
            type: integer
            nullable: false
            options:
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        youtubeLink:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
