App\Entity\WatchedCourses:
    repositoryClass: App\Repository\WatchedCoursesRepository
    type: entity
    table: watched_courses
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        watchedAt:
            type: datetime
            nullable: false
    manyToOne:
        course:
            targetEntity: Course
            joinColumn:
                name: course_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
